[INFO] Central web server started at [2025-04-05 18:48:48.181]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-05 18:48:48.636]
[INFO] Made request to synchronize dictionary at [2025-04-05 18:48:50.823]
[INFO] Created dictionary directory at [2025-04-05 18:48:50.839]
[INFO] Successfully saved new dictionary at [2025-04-05 18:48:50.847]
[INFO] Made request to crack password using dictionary method at [2025-04-05 18:48:50.868]
[INFO] Final cracking time with dictionary method was: 01:34:10. Cracking was successfull. at [2025-04-05 18:48:50.872]
[INFO] Central web server started at [2025-04-05 18:51:19.425]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-05 18:51:19.949]
[INFO] Made request to synchronize dictionary at [2025-04-05 18:51:30.638]
[INFO] Successfully saved new dictionary with size: 12 bytes at [2025-04-05 18:51:30.676]
[INFO] Made request to crack password using dictionary method at [2025-04-05 18:51:30.697]
[INFO] Final cracking time with dictionary method was: 01:34:10. Cracking was successfull. at [2025-04-05 18:51:30.702]
[INFO] Central web server started at [2025-04-05 18:54:32.457]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-05 18:54:32.968]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.10 at [2025-04-05 18:55:06.393]
[INFO] No dictionary found on server 192.168.0.10, starting synchronization at [2025-04-05 18:55:06.494]
[INFO] Successfully synchronized dictionary with server 192.168.0.10 at [2025-04-05 18:55:06.558]
[INFO] Successfully connected to calculating server 192.168.0.10 at [2025-04-05 18:55:06.570]
[INFO] Calculating server with IP address: 192.168.0.10 successfully connected to the central server at [2025-04-05 18:55:06.574]
[INFO] Central web server started at [2025-04-05 18:55:51.016]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-05 18:55:51.453]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.10 at [2025-04-05 18:56:02.931]
[INFO] Dictionary already exists on server 192.168.0.10 at path: /App/dictionary/dictionary-E21B6C5BAE3D9C39-2025-04-05.txt at [2025-04-05 18:56:03.034]
[INFO] Successfully connected to calculating server 192.168.0.10 at [2025-04-05 18:56:03.038]
[INFO] Calculating server with IP address: 192.168.0.10 successfully connected to the central server at [2025-04-05 18:56:03.052]
[INFO] Central web server started at [2025-04-05 18:56:49.486]
[INFO] Successfully connected to the PostgreSQL database instance at [2025-04-05 18:56:49.960]
[INFO] Made request to try to connect calculating server from IP address: 192.168.0.10 at [2025-04-05 18:57:01.230]
[INFO] Created dictionary directory at [2025-04-05 18:57:01.243]
[ERROR] No files found in directory path while trying to getting current dictionary hash at [2025-04-05 18:57:01.252]
[ERROR] Error while retrieving current dictionary hash: No files found in directory path. at [2025-04-05 18:57:01.257]
[INFO] No dictionary found on server 192.168.0.10, starting synchronization at [2025-04-05 18:57:01.342]
[ERROR] No files found in directory path while trying to getting current dictionary hash at [2025-04-05 18:57:01.348]
[ERROR] Failed to connect with calculating server 192.168.0.10 for reason: No files found in directory path. at [2025-04-05 18:57:01.358]
[ERROR] Cannot connect to calculating server due to: No files found in directory path. at [2025-04-05 18:57:01.364]
